### ISSUE TITLE
Error when retraining the object detection model

### ISSUE THREAD

**Issue by UV1999** [google-coral/tutorials#10]
This execution is for retraining an object detection model to recognize a set of classes using our very own custom dataset. All the prerequisites were downloaded and requirements were met. And as given in the tutorial, after starting the docker container, the download and configure the training data step given in the official Google-coral tutorial were skipped because we are using our very own custom dataset.

And by following the instructions given in the Google-coral website for configuring your own training data, we took our own images and labeled all those using LableMe to get the annotations in xml format. Then we converted the same to tf_record which is required to start training the model. 

There are a total of three classes namely person, mask, and face for which we also updated the label_map.pbtxt file. The model that we used here is the MobileNet SSD V1. The model was downloaded and we also changed the pipeline.config file pointing to our own custom tf_record, label_map.pbtxt file, and the mobilenet_ssd_v1 model checkpoint file.

1. When executing the ./retrain_detection_model.sh --num_training_steps ${NUM_TRAINING_STEPS} --num_eval_steps ${NUM_EVAL_STEPS},  after the initial stages, this warning arises stating that the Variable [global_steo] is not available in checkpoint.

![1](https://user-images.githubusercontent.com/29156063/95641661-42c36680-0ac1-11eb-9b41-759c95c240e3.jpg)

2. And just after executing the warning, the next error that arises is that Your CPU supports instructions that this TensorFlow binary was not compiled to use.

![2](https://user-images.githubusercontent.com/29156063/95641673-5242af80-0ac1-11eb-914b-5510dc59a123.jpg)

3. Finally, during the initial stages of training, there is this warning repeated twice after which the execution stops. The error reads that the Allocation of 737280000 exceeds 10% of system memory.

![3](https://user-images.githubusercontent.com/29156063/95641714-6edee780-0ac1-11eb-865e-e2d79cc4ee5a.jpg)

**Comment by Namburger** [comment]
@UV1999 
Hello, those are warnings rather than errors, mostly have to to with optimizations that your CPU can't supports or out of memory. You can ignore unless it causing problem. If it crashes, you'll need to increase swap or add more memory.

**Comment by UV1999** [comment]
Hi, I will share my PC specs and the dataset details below. Could you let me know that if my configuration is not suited for this training and how could I change the dataset to run training on my PC?

PC Specs:
Intel i7 7500U - 2 cores & 4 threads
8 GB DDR4 RAM
4 GB Nvidia GTX 950M Dedicated graphics card

Dataset:
3500 images
Annotated in Intel CVAT
Downloaded TFRecord from CVAT

**Comment by Namburger** [comment]
@UV1999 It really depends on your configuration and dataset but normally, for ML, you'd definitely want at least 16Gb of RAM. 
One way to lower memory usage of tensorflow is to use lower the "batchsize" param in your config to 1, training will be slower, but less memory usage. Did your training crashed?

Also, did you get to check this tutorial out? 
https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain
You see, on that tutorial, you'll take advantage to free google's GPU for your training and won't need to worry about your machine specs

**Comment by UV1999** [comment]
Yes, I guess the training crashed. After the Allocation of 73728000 exceeds 10% of system memory warning, I got another warning that read ./retrain_edaction_model.sh: line 58: 1460 Killed. Right after this warning, the execution of the retrain_detection_model.sh stopped. 

I checked out the colab tutorial but can I retrain the model in the tutorial using the custom dataset that I have mentioned above with 3500 images?

**Comment by Namburger** [comment]
oh, yeah, `1460 killed` is a direct kill signal from OOM killer, that means you were out of memory :/
You should be able to train with as much images as you want (on your machine or on colab) but you may need to lower the batch size to 1 as I suggested

[Edit] Yes, you can upload your own dataset to it

**Comment by UV1999** [comment]
Thanks for solving the doubts!

Let me try it out by lowering the batch size both on my machine and colab.

**Comment by Namburger** [comment]
No problems :)

**Comment by scottamain** [comment]
Hey @UV1999 I'm going to close this because there hasn't been any activity. If you're still having trouble with this specific issue, please reopen.
