### ISSUE TITLE
Training and converting a custom UNet network

### ISSUE THREAD

**Issue by ItsMeTheBee** [google-coral/tutorials#11]
Hey all!

I´m currently trying to train a custom UNet and convert it for the coral chip. But no matter what I try, the model always has many operations that can´t be compiled.
I´ve seen that you have UNet models available but since I need to be able to modify the model architecture I can´t simply retrain with these models.
Could you provide a tutorial/ guideline / basic python script with the model architecture you´ve been using? I just started using UNet so I´m not sure what the issue is and it would help me a lot since I found very little info on that topic.

**Comment by Namburger** [comment]
@ItsMeTheBee Hello!
Here is how I made that model: https://colab.research.google.com/drive/1CCSM2FLOtHx0dPr1HgHFX0yLAgpOs7eT?usp=sharing
Feel fee to tweak it for your own needs!
