### ISSUE TITLE
Object detection tutorial still uses Python 2

### ISSUE THREAD

**Issue by GrantPerkins** [google-coral/tutorials#12]
This version of Python has long since been deprecated. Should be migrated to Python3.x.

**Comment by Namburger** [comment]
Hello @GrantPerkins I believe everything is indeed already in python3, what make you think it is python2?

**Comment by GrantPerkins** [comment]
[retrain_detection_model.sh line 54](https://github.com/google-coral/tutorials/blob/f0bac57e68a2e14fdec3df8fffba533f5a53cc88/docker/object_detection/scripts/retrain_detection_model.sh#L54)

This line is using Python2, as shown here: [tensorflow/models source](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py)

**Comment by GrantPerkins** [comment]
I don't think this is a documentation issue.

**Comment by Namburger** [comment]
@GrantPerkins yes, it is calling python, but that doesn't mean that it is python2. It really depends on the system and aliases that youhave on that system. In the case of this docker image, python = python3.5:
```
root@d03435d18d36:/tensorflow/models/research# python3 --version 
Python 3.5.2
```
Furthermore, model_main.py is written in python3: https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py

**Comment by GrantPerkins** [comment]
Yep, all set.

**Comment by GrantPerkins** [comment]
@Namburger reviving old issue, but I realize that even though `python3` is in fact Python 3, the `python` command is used.

https://github.com/google-coral/tutorials/blob/3b6daa16ef67cc48062f444b4df88165ab636d94/docker/object_detection/scripts/retrain_detection_model.sh#L54

`python` refers to Python 2.7. Tensorflow is not installed for Python 3 in this Docker image.
