### ISSUE TITLE
Only 10 detections

### ISSUE THREAD

**Issue by hannes56a** [google-coral/tutorials#13]
Hi all,
I retrained the ssd_mobilNet_v1 model with own data (4 classes) (following the google tutorial for the coral chip: https://coral.ai/docs/edgetpu/retrain-detection/#using-the-coral-usb-accelerator).

Now I´m testing the new model on my test images with the "detect_image.py" script.
It basically works, but I got maximum 10 detections (boundingboxes). There are many more objects to find. I tested some things and there are every time maximum 10 detections in all (not 10 detections per class). If i "overpaint" these detections in the testimage, the model finds another 10 detections...

Perhaps some usefull information:
- An image, wich is shown as eval image in tensorboard with about 20 detections, has only 10 detections, if I test it as described above. 
- If I use the original "ssd_mobilnet_v1_quant" from google model zoo and test it as described above, i have more than 10 detections (tested with an image with many apples)

"max_detections_per_class" and "max_total_detections" in the "pipeline.config" for the retraining are both 100.

I do not find any parameter or reason for this behavior. Can please someone help me?

Greeting, Hannes

**Comment by hannes56a** [comment]
Nobody has an idea??

**Comment by scottamain** [comment]
Let's discuss at https://github.com/google-coral/tflite/issues/44
