### ISSUE TITLE
EfficientDet-Lite0 real-time capability

### ISSUE THREAD

**Issue by muxamilian** [google-coral/tutorials#14]
I've been following the tutorial [Retrain EfficientDet-Lite detector for the Edge TPU (TF2)](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb). I ran the resulting model on the Coral Dev Board and achieved a latency of ~60ms, which means I achieve less than 20 FPS. This was using EfficientDet-Lite0 and thus the smallest EfficientDet. 

Since I want to use the Google Coral for real-time object detection, this is insufficient for my needs. Is there a way to make EfficientDet perform in real-time on the Google Coral? Is it possible that something went wrong even though I followed the tutorial without any changes? If not, which other model is recommended for real-time object detection on the Coral using Tensorflow >2?

**Comment by manoj7410** [comment]
@muxamilian Can you first try to use the pre-trained models available at https://coral.ai/models/object-detection/ and see what latency are you getting ?
And which version of Dev board do you have, 4 GB or 1 GB ?

**Comment by hjonnala** [comment]
Hi @muxamilian Efficinet det model is taking more time on CPU. Please try the other models  available at https://coral.ai/models/object-detection/ and gstreamer examples from [exampless-camera](https://github.com/google-coral/examples-camera) repo.

USB accelerator:
```
hemanthj@hemath-glaptop:~/libcoral/out/k8/benchmarks/coral$ ./single_model_benchmark -model efficientdet-lite-salad_edgetpu.tflite 
2021-12-02 15:21:33
Running ./single_model_benchmark
Run on (4 X 3900 MHz CPU s)
CPU Caches:
  L1 Data 32K (x2)
  L1 Instruction 32K (x2)
  L2 Unified 256K (x2)
  L3 Unified 4096K (x1)
Load Average: 1.75, 1.90, 1.65
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model         20.6 ms         8.50 ms           78 efficientdet-lite-salad_edgetpu.tflite
```

Coral Dev Board:
```
mendel@tuned-rabbit:~$ ./single_model_benchmark -model efficientdet-lite-salad_edgetpu.tflite 
2021-12-02 23:22:59
Running ./single_model_benchmark
Run on (4 X 1500 MHz CPU s)
Load Average: 0.20, 0.06, 0.02
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model         71.7 ms         50.4 ms           13 efficientdet-lite-salad_edgetpu.tflite
```
