### ISSUE TITLE
Mobilenet v3 model tutorial

### ISSUE THREAD

**Issue by omerferhatt** [google-coral/tutorials#15]
Can someone add Mobilenet v3 model implementation on TF2 because Keras pre-trained model not working.

**Comment by omerferhatt** [comment]
Hello again, the main problem is
```model.input.set_shape((1,) + model.input.shape[1:])```

In MobileNetV2, constructed model can be compiled without editing. But in V3Small and V3Large, model input shape needs to be set before saving model. After setting batch shape, model compiled successfully.

**Comment by hjonnala** [comment]
Hi, It seems you found the solution. Are you still looking for Mobilenet v3 model implementation on TF2?

**Comment by omerferhatt** [comment]
Hello, actually no. It's working now. But it would be great if docs will be updated for newcomers.

**Comment by hjonnala** [comment]
Sure, we will make the changes when tutorial got updated with moblenetv3.

For others, for any edgetpu compiler conversion issues please refer to this [tutorial](https://github.com/google-coral/tutorials/blob/master/fix_conversion_issues_ptq_tf2.ipynb).

Thanks
