### ISSUE TITLE
SSD MobileNet V2 TD2.x Tutorial request 

### ISSUE THREAD

**Issue by ulrichMarco** [google-coral/tutorials#16]
### Description

On the official coral object detection models website, there is listed a SSD MobileNet V2 model which is generated with tf 2.x. 
Is it possible to get an tutorial how to retrain this model? Its because i have an Nvidia RTX 3080 which only supports Cuda 11+, and TF1.15,which is used in the tutorials only supports till Cuda 10.x .

### Issue Type

Documentation Feature Request

### Operating System

Linux, Ubuntu

### Coral Device

USB Accelerator, M.2 Accelerator with dual Edge TPU

### Programming Language

C++, Python 3.6

**Comment by hjonnala** [comment]
@ulrichMarco please check [tutorials repo](https://github.com/google-coral/tutorials) for [MobileNet v2](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb) tutorial with tf2.x

**Comment by ulrichMarco** [comment]
I did, there are only TF 1 tutorials for object detection. The one you linked is an image classification one.

**Comment by Naveen-Dodda** [comment]
Hi, 

I can see your problem to use RTX 3080. I tired to build a TF2.x tutorial but have due few roadblocks, we have postpone the plan.  But you can use following recommendations and try it your self it's fairly easy process to do. 

1. Main reason to drop TF2.x for tutorial is it supports less number of architectures suitable for edgetpu compared to TF1.x. 
you can take a look at supported backbones here https://github.com/tensorflow/models/blob/master/research/object_detection/builders/model_builder.py#L100  

2. You can use tutorial here https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb to train a model. 
3. in TF2.x you have to use Post Training Quantization to export a int8_tflite model. 
4. Finally compile it for edgetpu

Just two different steps to try it with TF2.x 


Let us know if you have any questions. Happy Training
