### ISSUE TITLE
pre-trained model is not used

### ISSUE THREAD

**Issue by tino926** [google-coral/tutorials#19]
I found that the pre-trained model is not used unless I modify "model_lib.py" according to this:
https://github.com/tensorflow/models/issues/8695#issuecomment-747905066

Maybe you should specify which commit of https://github.com/tensorflow/models you are used.

**Comment by hjonnala** [comment]
Hi @tino926  can you please specify which pre-trained model you are referring to? Thanks!

**Comment by hjonnala** [comment]
Closing the issue as it seems to be relevant to tensorflow/models repository.
