### ISSUE TITLE
Addition of object detection google colab-Reg

### ISSUE THREAD

**Issue by aswinkumar2019** [google-coral/tutorials#2]
Hello guys,
We tried to train object detection model using docker image provided in official tutorial.But,I think it is outdated and gives a lot of errors.
I heard from your support team that,you are working on a google colab for object detection too like image classification google colab.
Can you please give the approximate time frame for release of google coral object detection google colab?
In the mean time,is there any alternative for that docker image?
Regards,
Aswin Kumar

**Comment by luke-iqt** [comment]
I was just coming here to ask the same thing. I saw that there is an update Colab Notebook for TF2 . Any chance there is one coming for Object Detection too?

**Comment by aswinkumar2019** [comment]
I asked the Google customer support and they said, it is in works and, they declined to provide the approximate release date. BTW I asked it a long time ago.
I dont think it would be released.
@luke-iqt may I know, what are you currently using to train your object detection model for Google coral?
Regards,
Aswin Kumar

**Comment by luke-iqt** [comment]
@aswinkumar2019 I was able to follow the tutorial here and do the retraining:
https://coral.ai/docs/edgetpu/retrain-detection/
It uses a really old version TF, but it is in a Docker container so it works pretty well.

**Comment by natxopedreira** [comment]
+1 on this

I have a colab version working, and im retraining the face model provided by coral as a example but im not able to get a lower loss of <1, maybe im doing something wrong but i don't know. Having a sample to compare against sure will help

**Comment by aswinkumar2019** [comment]
@luke-iqt I had already tried the docker image which you have mentioned.
I got a lot of errors as it uses old version of tensorflow. 
I was unable to fix all the issues. 
Can you please mention the changes made and procedure you followed to successfully run that docker image?
Regards, 
Aswin Kumar

**Comment by natxopedreira** [comment]
@aswinkumar2019 I was able to use the docker image without issues..... what problem do you have?  Well to be honest i tried and get it running long ago, but now using colab

As far as i know there is no object detection api for tf2 so they must use tf1

take in mind also this [https://github.com/google-coral/tutorials/issues/4](https://github.com/google-coral/tutorials/issues/4)

**Comment by aswinkumar2019** [comment]
I got a lot of errors while following the instructions in the website (all because of outdated tensorflow version)
When I fix one, another comes and so on. 
I shall send the errors which I got when I get access to my pc

**Comment by natxopedreira** [comment]
@aswinkumar2019 

Im using tf 1.15 on colab .... what do you mean by outdated? The object detection api is only for tf1*

**Comment by aswinkumar2019** [comment]
Colab?, can you mention the colab link you are referring to?
I thought you are referring to the docker image

**Comment by aswinkumar2019** [comment]
https://github.com/google-coral/tutorials/blob/master/retrain_detection_qat_tf1.ipynb
Yeah a colab version for object detection is released. 
Thank you very much

**Comment by Namburger** [comment]
Hey guys, maybe after integrating to OD with TF2.0 I can put in a feature request for this. For now, I have made a mobildet tutorial that can be fully ran on colab if you are interested! 
https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain

**Comment by manoj7410** [comment]
Please see https://github.com/google-coral/tutorials for more tutorials that have been added.
