### ISSUE TITLE
GPU Tutorial For Object Detection

### ISSUE THREAD

**Issue by jbrownkramer** [google-coral/tutorials#5]
I feel like a common use case would be to fine tune a MobileNet with a GPU and then covert everything over to edgetpu.  I have created a docker that does this if there's any interest.

**Comment by laurentdebricon** [comment]
I am super interested ! 
(i don't get why the google colab tutorials provided are CPU :( still great though !)

**Comment by djalusic** [comment]
Hey @jbrownkramer, could you please share the tutorial? I'm currently trying to create it myself, without success.

**Comment by samsterckval** [comment]
I would also be interested!  @jbrownkramer did you share the docker or tutorial somewhere?

**Comment by Namburger** [comment]
I don't think we are pursuing an official GPU one at this time, but maybe you guys can use my unofficial one?
https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain
It's fully run-able on Colab!

**Comment by unsurv** [comment]
![Screenshot_20210112_203808](https://user-images.githubusercontent.com/43016521/115122177-e3399c80-9fb6-11eb-8b4c-327ccf50295b.jpg)

Hey, I found another way:

- follow the [official GPU docker tutorial](https://www.tensorflow.org/install/docker)

- in [this](https://github.com/google-coral/tutorials/blob/master/docker/object_detection/Dockerfile) file change `FROM tensorflow/tensorflow:1.12.0-rc2-devel` to  `FROM tensorflow/tensorflow:1.12.0-rc2-devel-gpu`

- When running your docker add `--gpus all` to your command. It should start like this: `sudo docker run --name edgetpu-detect --gpus all --rm -it --privileged -p 6006:6006` You should be able to see your NVIDIA GPU from inside the docker with `nvidia-smi`

- That's it. Follow the tutorial from coral for retraining.

**Comment by hjonnala** [comment]
Please check this colab GPU Tutorial for object detection: https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb
