### ISSUE TITLE
.zip file from gdrive

### ISSUE THREAD

**Issue by g30ba1** [google-coral/tutorials#6]
HI there, I´m trying to use my own dataset (Stored at google drive) for the "retrain_classification_ptq_tf2.ipynb" tutotial, but the notebook is NOT downloading any file.

Besides, I´m reading that  "tf.keras.utils.get_file" can´t handle .zip files properly.

Some link/advice?

**Comment by Namburger** [comment]
@g30ba1 
If you want to train on the colab, you can always upload your images to it and unzip it. 
If it's in google drive, simply mount the drive to your colab notebook, simply add this cell:
```
from google.colab import drive
drive.mount(‘/content/gdrive’)
```
It'll prompt you to authenticate your google drive account and then mount it on colab it self.
Another approach is to use flow_from_directory with out needing to call "tf.keras.utils.get_file".

**Comment by g30ba1** [comment]
Thank you very much, Namburguer 😀
