### ISSUE TITLE
map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by UV1999** [google-coral/tutorials#9]
Hey everyone, 

I am using the docker container method to retrain an object detection to deploy it on Google Coral. I am following the exact instructions available on the Google Coral official website. To train the model with the custom training dataset, I followed the instructions that were given on the Coral website. I have the dataset images along with its XML and trimap files. But when creating the tfrecord using the create_pet_tf_record.py file, I get this error where it says that there is no such file or directory for the map.pbtxt file. But as seen in the screenshot I have passed the parameters with the proper corresponding paths but I get this error. I have tried everything but still could not find a solution for the same. If someone else had the same problem, it would be so helpful if you can provide a solution.

I have also raised the same issue in the official tensorflow/models repository. The link to that issue is given below.
Link to Issue - https://github.com/tensorflow/models/issues/9327

![image](https://user-images.githubusercontent.com/29156063/94628736-6545ca80-02de-11eb-876c-1eb62345f5d8.png)

**Comment by Namburger** [comment]
@UV1999 Are you sure you didn't make any changes to the prepare_checkpoint_and_datasets.sh script? 
It should be looking for pets_label_map instead of map: 
https://github.com/google-coral/tutorials/blob/master/docker/object_detection/scripts/prepare_checkpoint_and_dataset.sh#L100

If you are configuring on your own datasets. please check your paths to that file again, the error basically states that it couldn't find that file. Also, the script is in docker, which is a VM, so the path that you gave from your host isn't going to be visible in docker.

**Comment by UV1999** [comment]
> @UV1999 Are you sure you didn't make any changes to the prepare_checkpoint_and_datasets.sh script?
> It should be looking for pets_label_map instead of map:
> https://github.com/google-coral/tutorials/blob/master/docker/object_detection/scripts/prepare_checkpoint_and_dataset.sh#L100
> 
> If you are configuring on your own datasets. please check your paths to that file again, the error basically states that it couldn't find that file. Also, the script is in docker, which is a VM, so the path that you gave from your host isn't going to be visible in docker.

Thanks for the reply and support!

But I have tried to change the name of the file and tried changing the path too. Still, the same issue persists, and can you please help me with what I am doing wrong here. Has this got anything to do with the mounting in a docker container?

**Comment by Namburger** [comment]
@UV1999 As I mentioned, the map file that you created is in your host machine so you won't be able to access it inside docker. 
One way to do this is to creates it inside docker instead, you can log into the docker image like this:
```
docker exec -it YOUR_IMAGE_NAME /bin/bash
```
If you are having issues with docker, perhaps you could checkout my colab tutorial also, it is a lot more clear:
https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain

**Comment by UV1999** [comment]
> @UV1999 As I mentioned, the map file that you created is in your host machine so you won't be able to access it inside docker.
> One way to do this is to creates it inside docker instead, you can log into the docker image like this:
> 
> ```
> docker exec -it YOUR_IMAGE_NAME /bin/bash
> ```
> 
> If you are having issues with docker, perhaps you could checkout my colab tutorial also, it is a lot more clear:
> https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain

Yes, I understand that

**Comment by UV1999** [comment]
> @UV1999 As I mentioned, the map file that you created is in your host machine so you won't be able to access it inside docker.
> One way to do this is to creates it inside docker instead, you can log into the docker image like this:
> 
> ```
> docker exec -it YOUR_IMAGE_NAME /bin/bash
> ```
> 
> If you are having issues with docker, perhaps you could checkout my colab tutorial also, it is a lot more clear:
> https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain

**Comment by scottamain** [comment]
Hey @UV1999 I'm going to close this because there hasn't been any activity. If you're still having trouble with this specific issue, please reopen.
